name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    name: Test Matrix Functionality
    steps:
      - uses: actions/checkout@v4

      - name: Test Basic Matrix
        id: basic-test
        uses: ./
        with:
          matrix: |
            - os: [ubuntu, macos]
              arch: [amd64, arm64]
          steps: |
            - name: Generate Output
              id: generate
              run: |
                echo "platform=$MATRIX_OS-$MATRIX_ARCH" >> $STEPS_OUTPUTS
          outputs: |
            - platform: ${ STEPS_GENERATE_PLATFORM }

      - name: Validate Basic Matrix Output
        run: |
          # Helper function to normalize and sort JSON arrays
          normalize_and_sort() {
            echo "$1" | jq -S 'sort_by(. | to_entries | sort_by(.key) | map(.value) | join("|"))'
          }

          # Normalize and sort both JSONs
          output_sorted=$(normalize_and_sort '${{ steps.basic-test.outputs.json }}')
          expected_sorted=$(normalize_and_sort '[{"platform":"ubuntu-amd64","os":"ubuntu","arch":"amd64"},{"platform":"ubuntu-arm64","os":"ubuntu","arch":"arm64"},{"platform":"macos-amd64","os":"macos","arch":"amd64"},{"platform":"macos-arm64","os":"macos","arch":"arm64"}]')
          
          # Compare the sorted JSONs
          if [ "$output_sorted" != "$expected_sorted" ]; then
            echo "JSON comparison failed. Showing both versions:"
            echo "Expected (sorted):"
            echo "$expected_sorted" | jq .
            echo "Got (sorted):"
            echo "$output_sorted" | jq .
            echo "Showing diff:"
            diff -u <(echo "$expected_sorted" | jq .) <(echo "$output_sorted" | jq .) || true
            exit 1
          fi

      - name: Test Array Outputs
        id: array-test
        uses: ./
        with:
          matrix: |
            - os: [ubuntu]
          steps: |
            - name: Multiple Outputs
              id: multi
              run: |
                echo "tags=v1.0" >> $STEPS_OUTPUTS
                echo "tags=latest" >> $STEPS_OUTPUTS
                echo "tags=stable" >> $STEPS_OUTPUTS
                echo "arch=x64" >> $STEPS_OUTPUTS
          outputs: |
            - tags: ${ STEPS_MULTI_TAGS }
            - arch: ${ STEPS_MULTI_ARCH }

      - name: Validate Array Outputs
        run: |
          output='${{ steps.array-test.outputs.json }}'
          expected='[{"os":"ubuntu","tags":["v1.0","latest","stable"],"arch":"x64"}]'
          
          # Compare the outputs
          if [ "$(echo "$output" | jq -S .)" != "$(echo "$expected" | jq -S .)" ]; then
            echo "Array output test failed. Showing both versions:"
            echo "Expected:"
            echo "$expected" | jq .
            echo "Got:"
            echo "$output" | jq .
            echo "Showing diff:"
            diff -u <(echo "$expected" | jq .) <(echo "$output" | jq .) || true
            exit 1
          fi

      - name: Test Step Dependencies
        id: dependency-test
        uses: ./
        with:
          matrix: |
            - env: [dev, prod]
              region: [us-east-1, us-west-2]
          steps: |
            - name: First Step
              id: first
              run: |
                echo "config=$MATRIX_ENV-config" >> $STEPS_OUTPUTS
            - name: Second Step
              id: second
              run: |
                echo "result=$MATRIX_REGION-$STEPS_FIRST_CONFIG" >> $STEPS_OUTPUTS
          outputs: |
            - config: ${ STEPS_FIRST_CONFIG }
            - result: ${ STEPS_SECOND_RESULT }

      - name: Validate Step Dependencies Output
        run: |
          # Helper function to normalize and sort JSON arrays
          normalize_and_sort() {
            echo "$1" | jq -S 'sort_by(. | to_entries | sort_by(.key) | map(.value) | join("|"))'
          }

          # Normalize and sort both JSONs
          output_sorted=$(normalize_and_sort '${{ steps.dependency-test.outputs.json }}')
          expected_sorted=$(normalize_and_sort '[{"config":"dev-config","result":"us-east-1-dev-config","env":"dev","region":"us-east-1"},{"config":"dev-config","result":"us-west-2-dev-config","env":"dev","region":"us-west-2"},{"config":"prod-config","result":"us-east-1-prod-config","env":"prod","region":"us-east-1"},{"config":"prod-config","result":"us-west-2-prod-config","env":"prod","region":"us-west-2"}]')
          
          # Compare the sorted JSONs
          if [ "$output_sorted" != "$expected_sorted" ]; then
            echo "JSON comparison failed. Showing both versions:"
            echo "Expected (sorted):"
            echo "$expected_sorted" | jq .
            echo "Got (sorted):"
            echo "$output_sorted" | jq .
            echo "Showing diff:"
            diff -u <(echo "$expected_sorted" | jq .) <(echo "$output_sorted" | jq .) || true
            exit 1
          fi

      - name: Test Error Handling
        id: error-test
        continue-on-error: true
        uses: ./
        with:
          matrix: |
            - test: [1, 2]
          steps: |
            - name: Fail Step
              id: fail
              run: |
                if [ "$MATRIX_TEST" = "2" ]; then
                  echo "Should fail for test=2"
                  exit 1
                fi
                echo "status=ok" >> $STEPS_OUTPUTS
          outputs: |
            - status: ${ STEPS_FAIL_STATUS }

      - name: Validate Error Handling
        run: |
          if [ "${{ steps.error-test.outcome }}" != "failure" ]; then
            echo "Expected error-test to fail"
            exit 1
          fi

      - name: Start Timer
        id: start-timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Test Parallel Execution (Default)
        id: parallel-test
        uses: ./
        with:
          matrix: |
            - number: [1, 2, 3, 4, 5]
          steps: |
            - name: Sleep Step
              id: sleep
              run: sleep 1

      - name: Validate Parallel Execution
        run: |
          end_time=$(date +%s)
          start_time=${{ steps.start-timer.outputs.start_time }}
          duration=$((end_time - start_time))
          
          # Should complete in roughly 1-2 seconds since running in parallel
          if [ $duration -gt 3 ]; then
            echo "Execution took too long ($duration seconds), expected parallel execution"
            exit 1
          fi

      - name: Start Timer
        id: start-timer-sequential
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Test Sequential Execution
        id: sequential-test
        uses: ./
        with:
          matrix: |
            - number: [1, 2, 3, 4, 5]
          max-parallel: 1
          steps: |
            - name: Sleep Step
              id: sleep
              run: sleep 1

      - name: Validate Sequential Execution
        run: |
          end_time=$(date +%s)
          start_time=${{ steps.start-timer-sequential.outputs.start_time }}
          duration=$((end_time - start_time))
          
          # Should take at least 5 seconds since running sequentially
          if [ $duration -lt 4 ]; then
            echo "Execution too fast ($duration seconds), expected sequential execution"
            exit 1
          fi

      - name: Test Matrix Include
        id: include-test
        uses: ./
        with:
          matrix: |
            - fruit: [apple, pear]
              animal: [cat, dog]
              include:
                - color: green
                - color: pink
                  animal: cat
                - fruit: apple
                  shape: circle
                - fruit: banana
                - fruit: banana
                  animal: cat
          steps: |
            - name: Echo Values
              id: echo
              run: |
                echo "combo=$MATRIX_FRUIT-$MATRIX_ANIMAL${MATRIX_COLOR:+-$MATRIX_COLOR}${MATRIX_SHAPE:+-$MATRIX_SHAPE}" >> $STEPS_OUTPUTS
          outputs: |
            - combo: ${ STEPS_ECHO_COMBO }

      - name: Test Real World Matrix
        id: real-world-test
        uses: ./
        with:
          matrix: |
            - os: [windows-latest, ubuntu-latest]
              node: [14, 16]
              include:
                - os: windows-latest
                  node: 16
                  npm: 6
          steps: |
            - name: Echo Configuration
              id: config
              run: |
                echo "setup=$MATRIX_OS-node$MATRIX_NODE${MATRIX_NPM:+-npm$MATRIX_NPM}" >> $STEPS_OUTPUTS
          outputs: |
            - setup: ${ STEPS_CONFIG_SETUP }

      - name: Validate Real World Matrix Output
        run: |
          # Helper function to normalize and sort JSON arrays
          normalize_and_sort() {
            echo "$1" | jq -S 'sort_by(. | to_entries | sort_by(.key) | map(.value) | join("|"))'
          }

          # Normalize and sort both JSONs
          output_sorted=$(normalize_and_sort '${{ steps.real-world-test.outputs.json }}')
          expected_sorted=$(normalize_and_sort '[
            {"os":"windows-latest","node":"14","setup":"windows-latest-node14"},
            {"os":"windows-latest","node":"16","npm":"6","setup":"windows-latest-node16-npm6"},
            {"os":"ubuntu-latest","node":"14","setup":"ubuntu-latest-node14"},
            {"os":"ubuntu-latest","node":"16","setup":"ubuntu-latest-node16"}
          ]')
          
          # Compare the sorted JSONs
          if [ "$output_sorted" != "$expected_sorted" ]; then
            echo "JSON comparison failed. Showing both versions:"
            echo "Expected (sorted):"
            echo "$expected_sorted" | jq .
            echo "Got (sorted):"
            echo "$output_sorted" | jq .
            echo "Showing diff:"
            diff -u <(echo "$expected_sorted" | jq .) <(echo "$output_sorted" | jq .) || true
            exit 1
          fi

      - name: Validate Include Output
        run: |
          output='${{ steps.include-test.outputs.json }}'
          
          # Check each expected combination
          expected_combinations=(
            # Matrix combinations with includes applied
            '{"fruit":"apple","animal":"cat","color":"green","shape":"circle","combo":"apple-cat-green-circle"}'
            '{"fruit":"apple","animal":"dog","color":"green","shape":"circle","combo":"apple-dog-green-circle"}'
            '{"fruit":"pear","animal":"cat","color":"green","combo":"pear-cat-green"}'
            '{"fruit":"pear","animal":"dog","color":"green","combo":"pear-dog-green"}'
            # Standalone includes
            '{"fruit":"banana","combo":"banana"}'
            '{"fruit":"banana","animal":"cat","combo":"banana-cat"}'
          )

          # Verify count matches
          count=$(echo "$output" | jq length)
          if [ "$count" -ne "${#expected_combinations[@]}" ]; then
            echo "Expected ${#expected_combinations[@]} combinations, but got $count"
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi

          # Check each combination exists
          failed=0
          for combination in "${expected_combinations[@]}"; do
            if ! echo "$output" | jq -e --arg combo "$combination" 'contains([($combo | fromjson)])' > /dev/null; then
              echo "Missing expected combination: $combination"
              failed=1
            fi
          done

          if [ $failed -eq 1 ]; then
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi

      - name: Test Include-Only Matrix
        id: include-only-test
        uses: ./
        with:
          matrix: |
            - include:
                - color: green
                - color: pink
                  animal: cat
                - fruit: apple
                  shape: circle
                - fruit: banana
                - fruit: banana
                  animal: cat
          steps: |
            - name: Echo Values
              id: echo
              run: |
                values=()
                [ -n "$MATRIX_COLOR" ] && values+=("$MATRIX_COLOR")
                [ -n "$MATRIX_ANIMAL" ] && values+=("$MATRIX_ANIMAL")
                [ -n "$MATRIX_FRUIT" ] && values+=("$MATRIX_FRUIT")
                [ -n "$MATRIX_SHAPE" ] && values+=("$MATRIX_SHAPE")
                echo "combo=$(IFS=-; echo "${values[*]}")" >> $STEPS_OUTPUTS
          outputs: |
            - combo: ${ STEPS_ECHO_COMBO }

      - name: Validate Include-Only Output
        run: |
          output='${{ steps.include-only-test.outputs.json }}'
          
          # Check each expected combination
          expected_combinations=(
            # Color includes get combined with other includes
            '{"color":"pink","animal":"cat","fruit":"apple","shape":"circle","combo":"pink-cat-apple-circle"}'
            '{"color":"green","fruit":"apple","shape":"circle","combo":"green-apple-circle"}'
            # Banana includes stay separate
            '{"fruit":"banana","animal":"cat","combo":"cat-banana"}'
          )

          # Verify count matches
          count=$(echo "$output" | jq length)
          if [ "$count" -ne "${#expected_combinations[@]}" ]; then
            echo "Expected ${#expected_combinations[@]} combinations, but got $count"
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi

          # Check each combination exists
          failed=0
          for combination in "${expected_combinations[@]}"; do
            if ! echo "$output" | jq -e --arg combo "$combination" 'contains([($combo | fromjson)])' > /dev/null; then
              echo "Missing expected combination: $combination"
              failed=1
            fi
          done

          if [ $failed -eq 1 ]; then
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi

      - name: Test Include From JSON
        id: json-include-test
        uses: ./
        with:
          matrix: |
            - include: ${{ steps.include-only-test.outputs.json }}
          steps: |
            - name: Echo Values
              id: echo
              run: |
                values=()
                [ -n "$MATRIX_COLOR" ] && values+=("$MATRIX_COLOR")
                [ -n "$MATRIX_ANIMAL" ] && values+=("$MATRIX_ANIMAL")
                [ -n "$MATRIX_FRUIT" ] && values+=("$MATRIX_FRUIT")
                [ -n "$MATRIX_SHAPE" ] && values+=("$MATRIX_SHAPE")
                echo "combo=$(IFS=-; echo "${values[*]}")" >> $STEPS_OUTPUTS
          outputs: |
            - combo: ${ STEPS_ECHO_COMBO }

      - name: Validate JSON Include Output
        run: |
          output='${{ steps.json-include-test.outputs.json }}'
          
          # Check each expected combination
          expected_combinations=(
            # Color includes get combined with other includes
            '{"color":"pink","animal":"cat","fruit":"apple","shape":"circle","combo":"pink-cat-apple-circle"}'
            '{"color":"green","fruit":"apple","shape":"circle","combo":"green-apple-circle"}'
            # Banana includes stay separate
            '{"fruit":"banana","animal":"cat","combo":"cat-banana"}'
          )

          # Verify count matches
          count=$(echo "$output" | jq length)
          if [ "$count" -ne "${#expected_combinations[@]}" ]; then
            echo "Expected ${#expected_combinations[@]} combinations, but got $count"
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi

          # Check each combination exists
          failed=0
          for combination in "${expected_combinations[@]}"; do
            if ! echo "$output" | jq -e --arg combo "$combination" 'contains([($combo | fromjson)])' > /dev/null; then
              echo "Missing expected combination: $combination"
              failed=1
            fi
          done

          if [ $failed -eq 1 ]; then
            echo "Full output:"
            echo "$output" | jq .
            exit 1
          fi 