name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    name: Test Matrix Functionality
    steps:
      - uses: actions/checkout@v4

      - name: Test Basic Matrix
        id: basic-test
        uses: ./
        with:
          matrix: |
            - os: [ubuntu, macos]
              arch: [amd64, arm64]
          steps: |
            - name: Generate Output
              id: generate
              run: |
                echo "platform=$MATRIX_OS-$MATRIX_ARCH" >> $STEPS_OUTPUTS
          outputs: |
            - platform: ${ STEPS_GENERATE_PLATFORM }

      - name: Validate Basic Matrix Output
        run: |
          # Create temp files for comparison
          echo '${{ steps.basic-test.outputs.json }}' | jq --sort-keys . > output.json
          echo '[{"platform":"ubuntu-amd64","os":"ubuntu","arch":"amd64"},{"platform":"ubuntu-arm64","os":"ubuntu","arch":"arm64"},{"platform":"macos-amd64","os":"macos","arch":"amd64"},{"platform":"macos-arm64","os":"macos","arch":"arm64"}]' | jq --sort-keys . > expected.json
          
          # Compare JSON content ignoring order
          if ! jq --argfile a output.json --argfile b expected.json -n '
            def post_sort: sort_by(paths) as $paths | reduce $paths[] as $p ([.]; . + [getpath($p)]); 
            def normalize: . as $x | reduce (paths(arrays)) as $p (.; setpath($p; getpath($p) | sort));
            ($a | normalize) as $a | ($b | normalize) as $b | 
            if $a == $b then true else 
              $a as $x | $b as $y | 
              ["Objects are different:", $x, "vs", $y] | halt_error
            end
          '; then
            echo "JSON comparison failed. Showing diff:"
            diff -u <(jq --sort-keys . output.json) <(jq --sort-keys . expected.json) || true
            exit 1
          fi

      - name: Test Step Dependencies
        id: dependency-test
        uses: ./
        with:
          matrix: |
            - env: [dev, prod]
              region: [us-east-1, us-west-2]
          steps: |
            - name: First Step
              id: first
              run: |
                echo "config=$MATRIX_ENV-config" >> $STEPS_OUTPUTS
            - name: Second Step
              id: second
              run: |
                echo "result=$MATRIX_REGION-$STEPS_FIRST_CONFIG" >> $STEPS_OUTPUTS
          outputs: |
            - config: ${ STEPS_FIRST_CONFIG }
            - result: ${ STEPS_SECOND_RESULT }

      - name: Validate Step Dependencies Output
        run: |
          # Create temp files for comparison
          echo '${{ steps.dependency-test.outputs.json }}' | jq --sort-keys . > output.json
          echo '[{"config":"dev-config","result":"us-east-1-dev-config","env":"dev","region":"us-east-1"},{"config":"dev-config","result":"us-west-2-dev-config","env":"dev","region":"us-west-2"},{"config":"prod-config","result":"us-east-1-prod-config","env":"prod","region":"us-east-1"},{"config":"prod-config","result":"us-west-2-prod-config","env":"prod","region":"us-west-2"}]' | jq --sort-keys . > expected.json
          
          # Compare JSON content ignoring order
          if ! jq --argfile a output.json --argfile b expected.json -n '
            def post_sort: sort_by(paths) as $paths | reduce $paths[] as $p ([.]; . + [getpath($p)]); 
            def normalize: . as $x | reduce (paths(arrays)) as $p (.; setpath($p; getpath($p) | sort));
            ($a | normalize) as $a | ($b | normalize) as $b | 
            if $a == $b then true else 
              $a as $x | $b as $y | 
              ["Objects are different:", $x, "vs", $y] | halt_error
            end
          '; then
            echo "JSON comparison failed. Showing diff:"
            diff -u <(jq --sort-keys . output.json) <(jq --sort-keys . expected.json) || true
            exit 1
          fi

      - name: Test Error Handling
        id: error-test
        continue-on-error: true
        uses: ./
        with:
          matrix: |
            - test: [1, 2]
          steps: |
            - name: Fail Step
              id: fail
              run: |
                if [ "$MATRIX_TEST" = "2" ]; then
                  echo "Should fail for test=2"
                  exit 1
                fi
                echo "status=ok" >> $STEPS_OUTPUTS
          outputs: |
            - status: ${ STEPS_FAIL_STATUS }

      - name: Validate Error Handling
        run: |
          if [ "${{ steps.error-test.outcome }}" != "failure" ]; then
            echo "Expected error-test to fail"
            exit 1
          fi 